services:
  - type: web
    name: go-backend
    env: go
    rootDir: backend       # Goのソースコードがあるディレクトリ
    buildCommand: go build -o app ./cmd/main.go
    startCommand: ./app
    autoDeploy: true       # Gitプッシュ時に自動デプロイ
    envVars:
      # ここはRenderダッシュボードで設定するなら空にしてもOK
      # - key: DB_HOST
      #   fromSecret: DB_HOST
      # - key: DB_USER
      #   fromSecret: DB_USER
      # - key: DB_PASSWORD
      #   fromSecret: DB_PASSWORD
      # - key: SECRET_KEY
      #   fromSecret: SECRET_KEY