services:
  - type: web
    name: go-backend
    env: go
    rootDir: backend              # ← ここを必ず指定！
    buildCommand: go build -o app ./cmd/main.go
    startCommand: ./app
    autoDeploy: true
    envVars:
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: root
      - key: DB_HOST
        value: db
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: goTodoAPP
      - key: SECRET_KEY
        value: 852768f975597fb81e172ba53c02eec44df9de2f81959a4d8ecebef1e92b3b8c